### ISSUE TITLE
Create Repo Documentation

### ISSUE THREAD

**Issue by achingachris** [achingachris/react-router-bootstrap-starter#73]
Documentation to Have the following:

1. How to install and use the template
2. Tools Used
3. Customizing The Template
4. Folder Structure
5. Reporting a bug or Feature request
6. How to Contribute
7. Any Other Important Stuff

**Comment by adetyaz** [comment]
hello, this is my first time contributing(probably my 3rd first time). Can I pick this up? I also have questions.

**Comment by achingachris** [comment]
> hello, this is my first time contributing(probably my 3rd first time). Can I pick this up? I also have questions.

Hi, @adetyaz I will appreciate your help. Please ask me anything, while I work on a plan to get this worked on!

**Comment by achingachris** [comment]
We will start with the README file for now

**Comment by adetyaz** [comment]
Hello, any updates on the guidelines. Also I noticed in the project the available components have already been documented.

**Comment by achingachris** [comment]
Hello, @adetyaz. Here are the contents that need to be documented:

1. Project Introduction
2. How to Download and Install The Packages
3. List of dependencies/packages used (and how to configure them if applicable)
4. How to locally run the template
5. Template Structure. i.e., what each file does
6. How to deploy the template on Netlify, Vercel.
7. Bugs and Issues that need attention
8. How to report an issue or a feature
9. Contribution Guidelines
10. List of Contributors

You can have them all inside the README file for now. Please let me know if the outline is clear

**Comment by adetyaz** [comment]
it is clear. 
anyways you didn't the second comment, so i'd follow the progress of the components when created.

**Comment by achingachris** [comment]
Hello, I’ll be done with the outline before end of day today. Sent from my iPhoneOn Jul 20, 2022, at 00:11, Adetayo ***@***.***> wrote:﻿
Hello, any updates on the guidelines. Also I noticed in the project the available components have already been documented.
