### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by njorogedaniel** [achingachris/react-router-bootstrap-starter#98]
How can I fix this error
![error](https://user-images.githubusercontent.com/11348537/221342453-ac9b4405-5b59-4192-a768-c9fe77037f03.PNG)

**Comment by njorogedaniel** [comment]
Aaah, I was able to resolve

**Comment by achingachris** [comment]
> Aaah, I was able to resolve

Interesting. How did you resolve it

**Comment by njorogedaniel** [comment]
Updated the node packages
